### ISSUE TITLE
No Alpha on Main Color and no Shadow

### ISSUE THREAD

**Issue by Laygendev** [Shrimpey/UltimateOutline#2]
Hi

Thanks for this shader, it's awesome.

The alpha on the main color it's not working, my gameobject still visible:

![alpha](https://user-images.githubusercontent.com/37774381/51406343-2f3bd380-1b59-11e9-80cb-c5915cce8e31.JPG)

And my shadow of my sphere it's not displayed, it's normal ?

![sphereshadow](https://user-images.githubusercontent.com/37774381/51406346-3367f100-1b59-11e9-9a8a-871c890d51fc.JPG)

Thanks for your help

**Comment by Shrimpey** [comment]
Hi,
When it comes to shadow I would have to work it out how to include proper
shadow casting, I will try to do it in the following days. The alpha thing
however was not included due to the way that shader works (because outline
creates another object behind the real object and therefore when alpha of
the main color would be equal to 0 and outline alpha set to non zero the
outline object would still be visible), however if you want to experiment
with how the alpha works you can just change the following:
In line 121 of UltimateOutline.shader add word "alpha" at the end, so it
looks like this:
#pragma surface surf Lambert alpha

Best regards,
Luke Kabat

pt., 18 sty 2019 o 19:42 Laygendev <notifications@github.com> napisał(a):

**Comment by Laygendev** [comment]
It's working fine for the alpha.

i'm just waiting for the shadow casting now.

Thanks :)

**Comment by Shrimpey** [comment]
Update:
It is not possible to combine shadow receiving and transparency - Unity simply forbids receiving shadows on transparent objects due to the way that ZBuffer works. I can try to implement version with shadows only, but then the outlines would lose the transparency as well.
